#!/bin/bash

showmess() {
	echo "################################################################################"
	echo "# $1"
	echo "################################################################################"
}

# Remove commons conflicts files (with stow)
rm ~/.Xresources
rm ~/.config/clipit/clipitrc
rm ~/.config/dunst/dunstrc
rm ~/.config/nitrogen/bg-saved.cfg
rm ~/.config/nitrogen/nitrogen.cfg
rm ~/.config/ranger/rc.conf
rm ~/.config/ranger/scope.sh
rm ~/.i3/config
rm ~/.xinitrc

#path=$(dirname $(realpath $0))

. ./get_computer_name

# Commons configuration
showmess "Apply commons configuration"
$path/mystow apply commons

# Computer configuration
if [ -e $path/../../../$COMPUTER ]; then
	showmess "Apply $COMPUTER configuration"
	$path/mystow apply $COMPUTER
fi
