#!/bin/bash

REPO=https://github.com/badele/docker-dotfiles.git

# Update
yaourt --noconfirm -Syyua

# System configuration
sudo echo "en_US.UTF-8 UTF-8" >>/etc/locale.gen && sudo echo "fr_FR.UTF-8 UTF-8" >>/etc/locale.gen
sudo locale-gen

# Install some desktop tools
yaourt --noconfirm -S xorg-server xorg-apps xorg-xinit arandr xautolock xdo numlockx compton xterm rxvt-unicode termite
yaourt --noconfirm -S imlib2 feh nitrogen w3m unclutter key-mon dmenu networkmanager-dmenu-git rofi spacefm dunst dunstify clipit

# Audio tools
yaourt --noconfirm -S pulseaudio pavucontrol pulseaudio-ctl

# Graphical tools
yaourt --noconfirm -S maim recordmydesktop peek byzanz

yaourt --noconfirm -S i3-gaps polybar-git nerd-fonts-complete ttf-material-design-icons chromium
# yaourt --noconfirm -S bspwm-git sxhkd-git polybar-git

# Install some terminal package
yaourt --noconfirm -S openssh ranger neovim stow highlight fzf ripgrep ctags the_silver_searcher tty-clock mpd ncmpcpp libmpdclient dmidecode

# Python
yaourt --noconfirm -S python-pip python-neovim python-virtualenvwrapper python-pywal termpalette-git
yaourt --noconfirm -S npm

# For Vim package
sudo npm i -g npm@5.6.0 # Fix temporary npm
sudo pip install jedi pylint vim-vint
sudo npm install -g fixjson jsonlint

# Configure ZSH
# powerline
yaourt --noconfirm -S antigen-git thefuck
yaourt --noconfirm -S neofetch highlight
yaourt --noconfirm -S shfmt
yaourt --noconfirm -S imagemagick

# Download some wallpapers, you can donwload more with download_wallpaper scripts
sudo mkdir /etc/skel/Images
sudo convert "https://static.pexels.com/photos/540518/pexels-photo-540518.jpeg" -strip -resize "1920x1080^" "/etc/skel/Images/mountain.jpg"
sudo convert "http://www.tokkoro.com/picsup/427348-anonymous-hd-widescreen-wallpapers-backgrounds.jpeg" -strip -resize "1920x1080^" "/etc/skel/Images/anonymous1_tokkoro.jpg"
sudo convert "http://www.tokkoro.com/picsup/2986141-anonymous-face-mask-minimalism-guy-fawkes-mask-hope-posters___mixed-wallpapers.jpg" -strip -resize "1920x1080^" "/etc/skel/Images/wanonymous2_tokkoro.jpg"
sudo convert "https://static.pexels.com/photos/51123/apple-education-school-knowledge-51123.jpeg" -strip -resize "1920x1080^" "/etc/skel/Images/apple1_pexels.jpg"

sudo cp "/etc/skel/Images/mountain.jpg" "/etc/skel/wallpaper.jpg"
