#!/bin/bash

BOOTSTRAP="n"
if [ "$1" = "bootstrap" ]; then
	BOOTSTRAP="y"
fi

REPO=https://github.com/badele/docker-dotfiles.git

# Overide yaourt CMD (disable not enough disk space in TMPFS)
mkdir -p $HOME/tmp
YAOURT="yaourt --tmp $HOME/tmp"

check_needed_packages() {
	# Check package needed
	INSTALLED=$($YAOURT -Q)
	TOINSTALL=""
	for PACKAGE in $INSTALL; do
		ISINSTALLED=$(echo "$INSTALLED" | grep "/$PACKAGE")
		if [ $? -eq 1 ]; then
			TOINSTALL="$TOINSTALL $PACKAGE"
		fi
	done

	echo "$TOINSTALL"
}

install_needed_packages() {
	# Install needed packages
	NEEDED=$(check_needed_packages)
	if [ "$NEEDED" != "" ]; then
		$YAOURT --noconfirm -S $NEEDED
	fi
}


# Update
$YAOURT --noconfirm -Syua

# System configuration
sudo sh -c 'echo "en_US.UTF-8 UTF-8" > /etc/locale.gen' && sudo sh -c 'echo "fr_FR.UTF-8 UTF-8" >>/etc/locale.gen'
sudo locale-gen

# Install some desktop tools
INSTALL="xorg-server xorg-apps xorg-xinit arandr xautolock xdo numlockx compton xterm rxvt-unicode termite"
INSTALL="$INSTALL imlib2 nomacs w3m unclutter key-mon  networkmanager-dmenu-git rofi spacefm dunst dunstify clipit"

# Video
INSTALL="$INSTALL ffmpeg mpv"

# Audio tools
INSTALL="$INSTALL pulseaudio pavucontrol pulseaudio-ctl"

# Graphical tools
INSTALL="$INSTALL imagemagick maim peek gifsicle-lossy  screenkey"

#INSTALL="$INSTALL i3-gaps dmenu-manjaro rootmenu polybar-git"
INSTALL="$INSTALL i3-gaps dmenu polybar-git"
INSTALL="$INSTALL nerd-fonts-complete ttf-material-design-icons chromium"

# Install some terminal package
INSTALL="$INSTALL openssh ranger neovim stow highlight ripgrep ctags the_silver_searcher tty-clock mpd ncmpcpp libmpdclient dmidecode"

# Python
INSTALL="$INSTALL python-pip python-neovim python-virtualenvwrapper python-pywal termpalette-git"
INSTALL="$INSTALL npm"

# Install needed packages step 1
install_needed_packages

# For Vim package
sudo npm i -g npm@5.6.0 # Fix temporary npm
sudo pip install jedi pylint vim-vint
sudo npm install -g fixjson jsonlint

# Configure ZSH
INSTALL="$INSTALL fzf fd antigen-git thefuck"

# powerline
INSTALL="$INSTALL neofetch highlight"
INSTALL="$INSTALL shfmt"

# Install needed packages step 2
install_needed_packages

# Download some wallpapers, you can donwload more with download_wallpaper scripts
if [ "$BOOTSTRAP" == "y" ]; then
	IMGPATH="/etc/skel"
	SUDO="sudo"
	sudo mkdir -p $IMGPATH/Images
else
	IMGPATH="$HOME"
	SUDO=""
	mkdir -p $IMGPATH/Images
fi

$SUDO convert "https://static.pexels.com/photos/540518/pexels-photo-540518.jpeg" -strip -resize "1920x1080^" "$IMGPATH/Images/mountain.jpg"
$SUDO convert "http://www.tokkoro.com/picsup/427348-anonymous-hd-widescreen-wallpapers-backgrounds.jpeg" -strip -resize "1920x1080^" "$IMGPATH/Images/anonymous1_tokkoro.jpg"
$SUDO convert "http://www.tokkoro.com/picsup/2986141-anonymous-face-mask-minimalism-guy-fawkes-mask-hope-posters___mixed-wallpapers.jpg" -strip -resize "1920x1080^" "$IMGPATH/Images/wanonymous2_tokkoro.jpg"
$SUDO convert "https://static.pexels.com/photos/51123/apple-education-school-knowledge-51123.jpeg" -strip -resize "1920x1080^" "$IMGPATH/Images/apple1_pexels.jpg"

$SUDO cp "$IMGPATH/Images/mountain.jpg" "$IMGPATH/wallpaper.jpg"
