#!/bin/bash

COMPUTER=""

if [ -e /x11docker/x11docker.CMD.sh ]; then
	export COMPUTER="x11docker"
fi

if [ -z "$COMPUTER" ] && [[ $(cat /sys/devices/virtual/dmi/id/product_name | grep "Latitude E5540") ]]; then
	export COMPUTER="dell"
fi

if [ -z "$COMPUTER" ] && [[ $(cat /sys/devices/virtual/dmi/id/product_name | grep "XPS 15 9570") ]]; then
	export COMPUTER="dellxps"
fi
