#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

MONITORS=$(xrandr -q | awk '/ connected/ {print $1}')
for m in $MONITORS; do
	MONITOR=$m polybar --reload bottom &
	MONITOR=$m polybar --reload top &
done
