#!/bin/bash

PWD=$(pwd)

# Check if in the dotfiles folder
if [ ! -f "$PWD/commons/.stow" ]; then
	echo "It seem not a dotfiles folder, please go to your root dotfiles folder"
	exit 1
fi

# Execute stow
if [ ! $# -ge 2 ]; then
	echo "Usage:"
	echo "$0 simulate commons"
	echo "$0 apply dell"
	exit 0
else
	NBARGS=$(($# - 2))
	OPTS=${@:3:$NBARGS}
	MODE=${@:1:1}
	ENV=${@:2:1}

	SIMULATE=""
	if [ "$MODE" == "simulate" ]; then
		SIMULATE="-v --simulate"
	fi

	if [ -d "$PWD/$ENV/user" ]; then
		# Sync files not compatible with stow.
		# ex: pulseaudio not compatible with hardlink
		#
		# Copy *.rsync files to home directory
		find $PWD/$ENV/user/ -name "*.rsync" -printf '%P\n' -exec cp -r --parent {} $HOME/ \;
		find $HOME/ -name "*.rsync" | sed -e "p;s/\.rsync//" | xargs -n2 mv 2>/dev/null

		# Copy stow user file to home directory
		stow --adopt -d $PWD/$ENV $SIMULATE -t $HOME $OPTS user

		if [ -e "$PWD/$ENV/postscript_user.sh" ]; then
			echo "Execute $ENV postscript_user.sh"
			$PWD/$ENV/postscript_user.sh
		fi
	fi

	if [ -d "$PWD/$ENV/system" ]; then
		sudo stow --adopt -d $PWD/$ENV $SIMULATE -t / $OPTS system

		if [ -e "$PWD/$ENV/postscript_system.sh" ]; then
			echo "Execute $ENV/postscript_system.sh"
			$PWD/$ENV/postscript_system.sh
		fi
	fi
fi
