#!/bin/sh
xrandr --output eDP1 --primary --mode 1600x900 --pos 480x1440 --rotate normal --output DP1 --off --output DP1-1 --mode 2560x1440 --pos 0x0 --rotate normal --output DP1-2 --off --output DP1-3 --off --output DP2 --off --output DP3 --off --output VIRTUAL1 --off
