#!/bin/sh
xrandr --output VIRTUAL1 --off --output DP3 --off --output eDP1 --primary --mode 1920x1080 --pos 0x1440 --rotate normal --output DP1 --off --output DP1-3 --off --output DP1-1 --off --output DP1-2 --mode 2560x1440 --pos 0x0 --rotate normal --output DP2 --off
