#!/bin/bash

NB=$(bspc query -M | wc -l)

if [[ "$NB" == 1 ]]; then
    # Ignore if in x11docker
    xrandr --listmonitors|grep default
    if [ $? -eq 0 ]; then
	    xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output DP1-3 --off --output DP1-2 --off --output DP1-1 --off
    fi
elif [[ "$NB" == 2 ]]; then
    xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output DP1-3 --mode 1680x1050 --pos 1366x0 --rotate normal --output DP1-2 --off --output DP1-1 --off
fi