#! /bin/sh
export mingap=15
export maxgap=20
export PANEL_HEIGHT=25

#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $maxgap
#bspc config top_padding $(($PANEL_HEIGHT-$maxgap))
#bspc config left_padding $maxgap
#bspc config right_padding $maxgap
#bspc config bottom_padding $maxgap

#Various settings
bspc config gapless_monocle false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle true
bspc config single_monocle true
bspc config paddingless_monocle false

#bspc config ignore_ewmh_focus      true
#bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
## Honor size hints: do not make windows smaller than they wish to be
#bspc config honor_size_hints true

##Color settings
bspc config focused_border_color "#1ABB9B"
bspc config normal_border_color "#2D2D2D"
#"#000000"
bspc config presel_feedback_color "#1ABB9B"
bspc config border_width 2

bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true #Some keybindings automatically enable and disable this setting

#Settings for manual splitting
bspc config split_ratio 0.52

###This creates and names desktops for multiple monitors.
init_screens
init_workspaces

bspc rule -r '*'
bspc rule -a URxvt -o desktop="8.term"
bspc rule -a Code desktop="6.code"
bspc rule -a Chromium desktop=7.web private=on

bspc rule -a key-mon sticky=on
#bspc rule -a screenkey --unmanage
bspc rule -a viewnior state=floating center=true
bspc rule -a libreoffice state=tiled
bspc rule -a 9menu border=off manage=off
bspc rule -a tint2 border=off manage=off

# Create user script for analysing windows class
echo "" >/tmp/.rules_cmd.log
bspc config external_rules_command "$HOME/.bin/bspwm_rules_command"

##  Autogap adjusts windowgap automatically according to the number of
##  windows on the desktop. Using it disables negative window gap.
#autogap &

##  This script balances all windows when new one is spawned
#euclid_balancer &

##Edge-switcher switches to next workspace when moves moves to the
##edge of the monitor (behavior similar to enlightenment)
#edge-switcher &

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command /usr/bin/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command /usr/bin/adjust-new-window

# Background
#nitrogen --restore &
color_scheme_reset

# Polybar
launch_bars &
